name: Preprocess Diabetes Data

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run preprocessing script
        run: python preprocessing/automate_Wildan-Mufid-Ramadhan.py
      - name: Upload preprocessed data
        uses: actions/upload-artifact@v3
        with:
          name: preprocessed-diabetes-data
          path: preprocessing/diabetes_preprocessed.csv

