name: Preprocess Diabetes Data

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run preprocessing script
        run: python preprocessing/automate_Wildan-Mufid-Ramadhan.py
      
      - name: Create Release with preprocessed data
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            preprocessing/diabetes_preprocessed.csv
          name: "${{ github.ref_name }}"
          body: |
            ## Preprocessed Diabetes Data
            
            This release contains the preprocessed diabetes dataset generated automatically.
            
            **Files included:**
            - `diabetes_preprocessed.csv` - Cleaned and preprocessed diabetes data
            
            **Generated on:** ${{ github.run_id }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}